FROM nvidia/cuda:11.7.1-runtime-ubuntu22.04

RUN apt update && apt-get -y install git wget \
    python3.10 python3.10-venv python3-pip \
    build-essential libgl-dev libglib2.0-0 wget
RUN ln -s /usr/bin/python3.10 /usr/bin/python
RUN useradd -ms /bin/bash usera
WORKDIR /app

RUN pip install notebook jupyterlab numpy pandas scikit-learn transformers torch torchvision torchaudio  --no-cache-dir
ADD ./start.sh ./
RUN chmod a+x ./start.sh
ENTRYPOINT [ "./start.sh" ]